---
project_name: kube-bench
env:
  - GO111MODULE=on
  - KUBEBENCH_CFG=/etc/kube-bench/cfg
builds:
  - main: main.go
    binary: kube-bench
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - "-X github.com/jonshaffer/kube-bench/cmd.KubeBenchVersion={{.Version}}"
      - "-X github.com/jonshaffer/kube-bench/cmd.cfgDir={{.Env.KUBEBENCH_CFG}}"
# Archive customization
dockers:
  -
    image_templates:
    - "hyperjon/kube-bench:v{{.Version}}-SNAPSHOT-{{.ShortCommit}}"
    - "public.ecr.aws/u7i1e6j3/kube-bench:v{{.Version}}-SNAPSHOT-{{.ShortCommit}}"
    - "hyperjon/kube-bench:latest"
    - "public.ecr.aws/u7i1e6j3/kube-bench:latest"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
    - "--build-arg=GOOS=linux"
    - "--build-arg=GOARCH=amd64"
    - "--platform=linux/amd64"
  -
    image_templates:
    - "hyperjon/kube-bench:v{{.Version}}-SNAPSHOT-{{.ShortCommit}}"
    - "public.ecr.aws/u7i1e6j3/kube-bench:v{{.Version}}-SNAPSHOT-{{.ShortCommit}}"
    - "hyperjon/kube-bench:latest"
    - "public.ecr.aws/u7i1e6j3/kube-bench:latest"
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: docker
    build_flag_templates:
    - "--build-arg=GOOS=linux"
    - "--build-arg=GOARCH=arm64"
    - "--platform=linux/arm64"
archives:
  - id: default
    format: tar.gz
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    files:
      - "cfg/**/*"
      - "cfg/config.yaml"
nfpms:
  -
    vendor: Aqua Security
    description: "The Kubernetes Bench for Security is a Go application that checks whether Kubernetes is deployed according to security best practices"
    maintainer: Yoav Rotem <yoav.rotem@aquasec.com>
    license: Apache-2.0
    homepage: https://github.com/aquasecurity/kube-bench
    file_name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    contents:
      - src: "cfg/**/*"
        dst: "/etc/kube-bench/cfg"
      - src: "cfg/config.yaml"
        dst: "/etc/kube-bench/cfg/config.yaml"
    formats:
      - deb
      - rpm
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
