---
env:
  - GO111MODULE=on
  - KUBEBENCH_CFG=/etc/kube-bench/cfg
builds:
  - id: kube-bench
    main: main.go
    binary: kube-bench
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - "-X github.com/aquasecurity/kube-bench/cmd.KubeBenchVersion={{.Version}}"
      - "-X github.com/aquasecurity/kube-bench/cmd.cfgDir={{.Env.KUBEBENCH_CFG}}"

dockers:
  - image_templates:
    - syncier/kube-bench
    - "syncier/kube-bench:{{ .Tag }}"
    binaries:
    - kube-bench
    builds:
    - kube-bench
    dockerfile: Dockerfile.goreleaser
    extra_files:
    - entrypoint.sh
    - cfg
# Archive customization
archives:
  - id: default
    format: tar.gz
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    files:
      - "cfg/**/*"
nfpms:
  -
    vendor: Aqua Security
    description: "The Kubernetes Bench for Security is a Go application that checks whether Kubernetes is deployed according to security best practices"
    license: Apache-2.0
    homepage: https://github.com/aquasecurity/kube-bench
    files:
      "cfg/**/*": "/etc/kube-bench/cfg"
    formats:
      - deb
      - rpm
