---
project_name: kube-bench
env:
  - GO111MODULE=on
  - KUBEBENCH_CFG=/etc/kube-bench/cfg
builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    binary: kube-bench
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - "-X github.com/jonshaffer/kube-bench/cmd.KubeBenchVersion={{.Version}}"
      - "-X github.com/jonshaffer/kube-bench/cmd.cfgDir={{.Env.KUBEBENCH_CFG}}"
# Archive customization
dockers:
  -
    image_templates:
      - "hyperjon/kube-bench:v{{.Version}}-amd64"
      - "public.ecr.aws/u7i1e6j3/kube-bench:v{{.Version}}-amd64"
      - "hyperjon/kube-bench:latest"
      - "public.ecr.aws/u7i1e6j3/kube-bench:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - cfg
      - entrypoint.sh
  -
    image_templates:
      - "hyperjon/kube-bench:v{{.Version}}-arm64v8"
      - "public.ecr.aws/u7i1e6j3/kube-bench:v{{.Version}}-arm64v8"
      - "hyperjon/kube-bench:latest"
      - "public.ecr.aws/u7i1e6j3/kube-bench:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    extra_files:
      - cfg
      - entrypoint.sh
  -
    image_templates:
      - "hyperjon/kube-bench:v{{.Version}}-armv6"
      - "public.ecr.aws/u7i1e6j3/kube-bench:v{{.Version}}-armv6"
      - "hyperjon/kube-bench:latest"
      - "public.ecr.aws/u7i1e6j3/kube-bench:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v6"
    extra_files:
      - cfg
      - entrypoint.sh
  -
    image_templates:
      - "hyperjon/kube-bench:v{{.Version}}-armv7"
      - "public.ecr.aws/u7i1e6j3/kube-bench:v{{.Version}}-armv7"
      - "hyperjon/kube-bench:latest"
      - "public.ecr.aws/u7i1e6j3/kube-bench:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v7"
    extra_files:
      - cfg
      - entrypoint.sh
docker_manifests:
  -
    name_template: hyperjon/kube-bench:v{{.Version}}
    image_templates:
      - "hyperjon/kube-bench:latest"
      - "hyperjon/kube-bench:v{{.Version}}-amd64"
      - "hyperjon/kube-bench:v{{.Version}}-arm64v8"
      - "hyperjon/kube-bench:v{{.Version}}-armv6"
      - "hyperjon/kube-bench:v{{.Version}}-armv7"
archives:
  - id: default
    format: tar.gz
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    files:
      - "cfg/**/*"
      - "cfg/config.yaml"
nfpms:
  -
    vendor: Aqua Security
    description: "The Kubernetes Bench for Security is a Go application that checks whether Kubernetes is deployed according to security best practices"
    maintainer: Yoav Rotem <yoav.rotem@aquasec.com>
    license: Apache-2.0
    homepage: https://github.com/aquasecurity/kube-bench
    file_name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    contents:
      - src: "cfg/**/*"
        dst: "/etc/kube-bench/cfg"
      - src: "cfg/config.yaml"
        dst: "/etc/kube-bench/cfg/config.yaml"
    formats:
      - deb
      - rpm
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
