---
project_name: kube-bench
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - KUBEBENCH_CFG=/etc/kube-bench/cfg
builds:
  - main: main.go
    binary: kube-bench
    tags:
      - osusergo
      - netgo
      - static_build
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - 6
      - 7
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X github.com/aquasecurity/kube-bench/cmd.KubeBenchVersion={{.Version}}"
      - "-X github.com/aquasecurity/kube-bench/cmd.cfgDir={{.Env.KUBEBENCH_CFG}}"
# Archive customization
archives:
  - id: default
    format: tar.gz
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    files:
      - "cfg/**/*"
      - "cfg/config.yaml"
nfpms:
  -
    vendor: Aqua Security
    description: "The Kubernetes Bench for Security is a Go application that checks whether Kubernetes is deployed according to security best practices"
    maintainer: Yoav Rotem <yoav.rotem@aquasec.com>
    license: Apache-2.0
    homepage: https://github.com/aquasecurity/kube-bench
    file_name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    contents:
      - src: "cfg/**/*"
        dst: "/etc/kube-bench/cfg"
      - src: "cfg/config.yaml"
        dst: "/etc/kube-bench/cfg/config.yaml"
    formats:
      - deb
      - rpm
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
