env:
  - GO111MODULE=on
builds:
  - main: main.go
    binary: kube-bench
    goos:
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
nfpm:
  vendor: Aqua Security
  description: "The Kubernetes Bench for Security is a Go application that checks whether Kubernetes is deployed according to security best practices"
  license: Apache-2.0
  homepage: https://github.com/aquasecurity/kube-bench
  formats:
    - deb
    - rpm
