--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-bench
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-psp-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user
subjects:
- kind: ServiceAccount
  name: kube-bench
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-bench-config
data:
  config.yaml: |
    master:
      components:
        - apiserver
        - scheduler
        - controllermanager
        - etcd 
        # kubernetes is a component to cover the config file /etc/kubernetes/config that is referred to in the benchmark
        - kubernetes

      kubernetes:
        defaultconf: /etc/kubernetes/manifests/

      apiserver:
        bins:
          - "hyperkube apiserver"
        defaultconf: /etc/kubernetes/manifests/k8s-api-server.yaml

      scheduler:
        bins:
          - "hyperkube scheduler"
        defaultconf: /etc/kubernetes/manifests/k8s-scheduler.yaml

      controllermanager:
        bins:
          - "hyperkube controller-manager"
        defaultconf: /etc/kubernetes/manifests/k8s-controller-manager.yaml

      etcd:
        optional: true
        bins:
          - "etcd"
        defaultconf: /etc/systemd/system/etcd3.service

    node:
      components:
        - kubelet
        - proxy
        # kubernetes is a component to cover the config file /etc/kubernetes/config that is referred to in the benchmark
        - kubernetes

      kubernetes:
        defaultconf: /etc/kubernetes/config/    

      kubelet:
        bins:
          - "hyperkube kubelet"
        defaultsvc: /etc/systemd/system/k8s-kubelet.service
        defaultconf: /etc/systemd/system/k8s-kubelet.service

      proxy:
        bins:
          - "hyperkube proxy"
        confs:
          - /etc/kubernetes/config/proxy-config.yml
          - /srv/kube-proxy-ds.yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench-node
  namespace: default
spec:
  template:
    spec:
      hostPID: true
      serviceAccount: kube-bench
      containers:
      - name: kube-bench
        image: quay.io/giantswarm/kube-bench:0.0.1
        args:
        - node
        - --version
        - "1.11"
        - --json
        - "true"
        volumeMounts:
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
        - name: etc-systemd
          mountPath: /etc/systemd
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: srv-kubernetes
          mountPath: /srv
      restartPolicy: Never
      volumes:
      - name: var-lib-kubelet
        hostPath:
          path: "/var/lib/kubelet"
      - name: etc-systemd
        hostPath:
          path: "/etc/systemd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: srv-kubernetes
        hostPath:
          path: "/srv"
