# Service account role required for 242395

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-bench-sa
  namespace: kube-bench

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-bench-list-pods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
    resourceNames: []  # Can't use labels here, enforced via RBAC + admission controls
  # - apiGroups: [""]
  #   resources: ["pods"]
  #   verbs: ["get"]
  #   resourceNames: []  # For explicit pod access if needed

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-bench-sa-binding
subjects:
  - kind: ServiceAccount
    name: kube-bench-sa
    namespace: kube-bench
roleRef:
  kind: ClusterRole
  name: kube-bench-list-pods
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
spec:
  template:
    spec:
      serviceAccountName: kube-bench-sa  
      hostPID: true
      containers:
        - name: kube-bench
          imagePullPolicy: Always
          # Push the image to your ECR and then refer to it here
          # image: <ID.dkr.ecr.region.amazonaws.com/aquasec/kube-bench:ref>
          image: us-docker.pkg.dev/dev-frm-core/dev-frm/kube-bench:gke-stig
          # To send findings to AWS Security Hub, refer to `job-eks-asff.yaml` instead
          command:
            [
              "kube-bench",
              "run",
              "--benchmark",
              "gke-stig-kubernetes-v2r2",
              "-v",
              "10",
            ]
          volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
            - name: home-kubernetes
              mountPath: /home/kubernetes
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
        - name: home-kubernetes
          hostPath:
            path: "/home/kubernetes"
