---
site_name: Kube-bench
site_url: https://aquasecurity.github.io/kube-bench/
site_description: Checks whether Kubernetes is deployed according to security best practices as defined in the CIS Kubernetes Benchmark
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/aquasecurity/kube-bench/
edit_uri: ""

nav:
  - Overview: index.md
  - Getting Started:
      - Installation: Installation.md
      - Platforms: Platforms.md
      - How to run: Running.md
      - ASFF: asff.md
  - Flags: Flags_and_commands.md
  - Configuration Options:
      - Understanding the yamls: Controls.md
      - Architecture: Architecture.md
  - Contributing: Contributing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

extra:
  generator: false
  version:
    method: mike
    provider: mike

theme:
  name: material
  language: 'en'
  logo: images/kube-bench-logo-only.png

plugins:
  - search
  - macros
