---
## Version-specific settings that override the values in cfg/config.yaml

master:
  apiserver:
    bins:
      - openshift start master api
      - hypershift openshift-kube-apiserver

  scheduler:
    bins:
      - "openshift start master controllers"
      - "hyperkube kube-scheduler"
    confs:
      - /etc/origin/master/scheduler.json

  controllermanager:
    bins:
      - "openshift start master controllers"
      - "hypershift openshift-controller-manager"

  etcd:
    bins:
      - openshift start etcd

node:
  svcs:
    - /etc/systemd/system/atomic-openshift-node.service
    - /etc/systemd/system/origin-node.service
  proxy:
    bins:
      - openshift start network
