---
## Version-specific settings that override the values in cfg/config.yaml

node:
  kubelet:
    defaultconf: "/etc/kubernetes/kubelet-config.yaml"
    defaultkubeconfig: "/var/lib/kubelet/kubeconfig"
