---
## Version-specific settings that override the values in cfg/config.yaml
## These settings are required if you are using either --asff option to report findings to AWS Security Hub or --sns to report to AWS SNS topic
## AWS account number is required.
AWS_ACCOUNT: "<AWS_ACCT_NUMBER>"
## AWS region is required.
AWS_REGION: "<AWS_REGION>"
## EKS Cluster ARN is required.
CLUSTER_ARN: "<AWS_CLUSTER_ARN>"
## SNS Topic ARN ( required if --sns flag is set )
SNSTOPIC_ARN: "<AWS_SNSTOPIC_ARN>"
