---
## Version-specific settings that override the values in cfg/config.yaml

master:
  components:
    - apiserver
    - kubelet
    - scheduler
    - controllermanager
    - etcd
    - policies
  kubelet:
    bins:
      - kubelet
node:
  kubelet:
    defaultkubeconfig: "/node/etc/kubernetes/ssl/kubecfg-kube-node.yaml"
    defaultcafile: "/node/etc/kubernetes/ssl/kube-ca.pem"
    bins:
      - kubelet
  proxy:
    defaultkubeconfig: "/node/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml"
