name: Deploy the dev documentation
on:
  push:
    paths:
      - 'docs/**'
      - mkdocs.yml
    branches:
      - main
jobs:
  deploy:
    name: Deploy the dev documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mike
          pip install mkdocs-macros-plugin
        env:
          GH_TOKEN: ${{ secrets.MKDOCS_AQUA_BOT }}
      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Deploy the dev documents
        run: mike deploy --push dev
